[project]
name = "uot-matching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "ott-jax>=0.5.1",
    "pandas>=2.3.1",
    "sentence-transformers>=5.1.0",
]
